### PR TITLE
Added a new changes in files

### PR DESCRIPTION
**Pull request by Murtaza-Farooqui**
Made changes and made about, home and contact responsive.
Please accept and merge the pull request

### CODE REVIEW

**Comment by Anirudha06** [comment]
Hacktoberfest-accepted

**Comment by Murtaza-Farooqui** [comment]
Screenshot (1)
Hi,
I am getting this message on hactoberfest website.
How can I solve?

**Comment by Murtaza-Farooqui** [comment]
Screenshot (2)

**Comment by Anirudha06** [comment]
Hacktoberfest-accepted

**Pull request merged**
